#include "ClientService.hpp"
#include <iostream>
#include <optional>

namespace api {
namespace services {

ClientService::ClientService(std::shared_ptr<datafeed::SAdapter> adapter)
    : adapter_(std::move(adapter))
{
}

std::optional<dto::ClientResponseDto> ClientService::getClientById(const std::string& tenant_id) {
    if (!adapter_ || !adapter_->is_connected() || tenant_id.empty()) {
        return std::nullopt;
    }
    auto clientOpt = adapter_->get_client_by_id(tenant_id);
    if (!clientOpt) {
        return std::nullopt;
    }
    return toDto(*clientOpt);
}

std::vector<dto::ClientResponseDto> ClientService::getClients() {
    if (!adapter_ || !adapter_->is_connected()) {
        return {};
    }
    auto clients = adapter_->get_clients_by_condition("");
    std::vector<dto::ClientResponseDto> dtos;
    dtos.reserve(clients.size());
    for (const auto& client : clients) {
        dtos.push_back(toDto(client));
    }
    return dtos;
}

std::optional<dto::ClientResponseDto> ClientService::createClient(const dto::ClientResponseDto& clientDto) {
    if (!adapter_ || !adapter_->is_connected()) {
        return std::nullopt;
    }
    datafeed::Client client;
    client.client_name = clientDto.client_name;
    client.plan = clientDto.plan;
    client.status = clientDto.status;
    client.auth_subject = clientDto.auth_subject;
    client.ip_address = clientDto.ip_address;
    client.user_agent = clientDto.user_agent;
    // Note: tenant_id is generated by the database, so we don't set it in the input.
    auto createdOpt = adapter_->create_client(client);
    if (!createdOpt) {
        return std::nullopt;
    }
    return toDto(*createdOpt);
}

bool ClientService::updateClient(const dto::ClientResponseDto& clientDto) {
    if (!adapter_ || !adapter_->is_connected() || clientDto.tenant_id.empty()) {
        return false;
    }
    datafeed::Client client;
    client.tenant_id = clientDto.tenant_id;
    client.client_name = clientDto.client_name;
    client.plan = clientDto.plan;
    client.status = clientDto.status;
    client.auth_subject = clientDto.auth_subject;
    client.ip_address = clientDto.ip_address;
    client.user_agent = clientDto.user_agent;
    // Note: we don't update created_at, updated_at is set by the database.
    return adapter_->update_client(client);
}

bool ClientService::deleteClient(const std::string& tenant_id) {
    if (!adapter_ || !adapter_->is_connected() || tenant_id.empty()) {
        return false;
    }
    return adapter_->delete_client(tenant_id);
}

dto::ClientResponseDto ClientService::toDto(const datafeed::Client& client) {
    dto::ClientResponseDto dto;
    dto.tenant_id = client.tenant_id;
    dto.client_name = client.client_name;
    dto.plan = client.plan;
    dto.status = client.status;
    dto.created_at = client.created_at;
    dto.updated_at = client.updated_at;
    dto.last_seen_at = client.last_seen_at;
    dto.auth_subject = client.auth_subject;
    dto.ip_address = client.ip_address;
    dto.user_agent = client.user_agent;
    return dto;
}

} // namespace services
} // namespace api